[package]
name = "ftt"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.1"
serde = { version = "1", features = ["derive"] }
field_count = "0.1.1"
regex = "1.11.1"
serde_json = "1.0.142"
clap = { version = "4.5.45", features = ["derive"] }
